In [141]:
import pandas as pd
import os
import random
from collections import Counter
import numpy as np

### common function

In [5]:
def getValusCounts(df,col,minValue):
    value_counts = df[col].value_counts()
    filtered_counts = value_counts[value_counts >= minValue].sort_index()
    result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})
    return result_df.to_dict('records')

In [32]:
def getValueCountsStatisticalData(data,type):
    numbers = [float(item['num']) for item in data]
    # 计算最大值、最小值、平均值
    max_value = max(numbers)
    min_value = min(numbers)
    avg_value = sum(numbers) / len(numbers)
    
    # 计算中位数
    numbers.sort()
    n = len(numbers)
    if n % 2 == 0:
        median = (numbers[n // 2 - 1] + numbers[n // 2]) / 2
    else:
        median = numbers[n // 2]
    
    # 计算众数
    mode_value = Counter(numbers).most_common(1)[0][0]
    return [type,max_value,min_value,avg_value,median,mode_value]

In [40]:
def getNumColStatisticalData(data,type):
    numbers = data.tolist()
    # 计算最大值、最小值、平均值
    max_value = max(numbers)
    min_value = min(numbers)
    avg_value = sum(numbers) / len(numbers)
    
    # 计算中位数
    numbers.sort()
    n = len(numbers)
    if n % 2 == 0:
        median = (numbers[n // 2 - 1] + numbers[n // 2]) / 2
    else:
        median = numbers[n // 2]
    
    # 计算众数
    mode_value = Counter(numbers).most_common(1)[0][0]
    return [type,max_value,min_value,avg_value,median,mode_value]

In [48]:
def getBoolColStatisticalData(data,type):
    my_list = data.tolist()
    # 初始化计数器
    true_count = 0
    false_count = 0
    
    # 遍历列表并统计True和False的数量
    for item in my_list:
        if item is True:
            true_count += 1
        elif item is False:
            false_count += 1
    
    # 计算占比
    total = true_count + false_count
    true_percentage = (true_count / total) * 100
    false_percentage = (false_count / total) * 100
    return [type,true_percentage,false_percentage]

### business

In [158]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business_mf.csv')

In [24]:
result_1_city_sd = getValueCountsStatisticalData(getValusCounts(df,"city",86),"VARCHAR")

In [26]:
result_1_state_sd = getValueCountsStatisticalData(getValusCounts(df,"state",0),"VARCHAR")

In [41]:
result_1_stars_sd = getNumColStatisticalData(df["stars"],"FLOAT")

In [43]:
result_1_review_sd = getNumColStatisticalData(df["review"],"INT")

In [45]:
result_1_favorites_sd = getNumColStatisticalData(df["favorites"],"INT")

In [47]:
result_1_avgspend_sd = getNumColStatisticalData(df["avgspend"],"INT")

In [49]:
result_1_popular_sd = getBoolColStatisticalData(df["popular"],"BOOL")

In [106]:
result_1_popular_sd

['BOOL', 67.04205853184507, 32.95794146815492]

In [111]:
business_finally = [
    ["business.city"] + result_1_city_sd + [None] * 2,
    ["business.state"] + result_1_state_sd + [None] * 2,
    ["business.stars"] + result_1_stars_sd +[None] * 2,
    ["business.review"] + result_1_review_sd + [None] * 2,
    ["business.favorites"] + result_1_favorites_sd + [None] * 2,
    ["business.avgspend"] + result_1_avgspend_sd + [None] * 2,
    ["business.popular"] +[result_1_popular_sd[0]] +[None] * 5+result_1_popular_sd[1:3]
]

In [159]:
df

,business_id,name,address,city,state,code,stars,review,favorites,avgspend,popular,categories,feature
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,5.0,7,220,160,True,"Doctors, Traditional Chinese Medicine, Naturop...","[0.5149855613708496, -0.2046436369419098, -0.3..."
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,3.0,15,36,27,False,"Shipping Centers, Local Services, Notaries, Ma...","[0.2881472706794739, -0.04402739554643631, -0...."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,3.5,22,134,56,True,"Department Stores, Shopping, Fashion, Home & G...","[0.49464067816734314, 0.022908760234713554, -0..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,4.0,80,98,49,True,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","[0.47613540291786194, 0.04090013727545738, -0...."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,4.5,13,215,116,True,"Brewpubs, Breweries, Food","[0.6412854790687561, 0.15557944774627686, -0.2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150238,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,3.0,13,22,22,False,"Nail Salons, Beauty & Spas","[0.4360079765319824, 0.15860453248023987, -0.6..."
150239,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,4.0,5,87,59,True,"Pets, Nurseries & Gardening, Pet Stores, Hobby...","[0.43686267733573914, 0.10853110998868942, -0...."
150240,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,3.5,8,77,67,False,"Shopping, Jewelry, Piercing, Toy Stores, Beaut...","[0.34829986095428467, 0.06677868217229843, -0...."
150241,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,4.0,24,115,70,False,"Fitness/Exercise Equipment, Eyewear & Optician...","[0.45862674713134766, 0.17515017092227936, -0...."
150242,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,4.5,9,164,136,True,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo","[0.19764001667499542, 0.24613741040229797, -0...."

### review

In [51]:
base_directory = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review'
base_filename = 'part_'
file_extension = '.csv'

In [52]:
dfs = []

# 使用循环读取part_1.csv到part_40.csv文件
for i in range(1, 41):  # 从1到40，包含40
    file_name = f"{base_filename}{i}{file_extension}"  # 构建文件名
    file_path = os.path.join(base_directory, file_name)  # 构建完整的文件路径
    df = pd.read_csv(file_path)  # 读取CSV文件
    dfs.append(df)  # 将DataFrame添加到列表中

In [53]:
df_1 = pd.concat(dfs, ignore_index=True)

In [55]:
result_2_stars_sd = getNumColStatisticalData(df_1["stars"],"FLOAT")

In [58]:
result_2_useful_sd = getNumColStatisticalData(df_1["useful"],"FLOAT")

In [60]:
result_2_funny_sd = getNumColStatisticalData(df_1["funny"],"FLOAT")

In [62]:
result_2_cool_sd = getNumColStatisticalData(df_1["cool"],"FLOAT")

In [64]:
result_2_likes_sd = getNumColStatisticalData(df_1["likes"],"INT")

In [65]:
result_2_dislikes_sd = getNumColStatisticalData(df_1["dislikes"],"INT")

In [66]:
result_2_views_sd = getNumColStatisticalData(df_1["views"],"INT")

In [67]:
result_2_reads_sd = getBoolColStatisticalData(df_1["reads"],"BOOL")

In [113]:
review_finally = [
    ["review.starts"]+result_2_stars_sd+[None] * 2,
    ["review.useful"]+result_2_useful_sd+[None] * 2,
    ["review.funny"]+result_2_funny_sd+[None] * 2,
    ["review.cool"]+result_2_cool_sd+[None] * 2,
    ["review.likes"]+result_2_likes_sd+[None] * 2,
    ["review.dislikes"]+result_2_dislikes_sd+[None] * 2,
    ["review.views"]+result_2_views_sd+[None] * 2,
    ["review.reads"] +[result_2_reads_sd[0]] +[None] * 5+result_2_reads_sd[1:3]
]

In [114]:
review_finally

[['review.starts', 'FLOAT', 5.0, 1.0, 3.955599, 5.0, 5.0, None, None],
 ['review.useful', 'FLOAT', 404.0, -1.0, 0.6783825, 0.0, 0.0, None, None],
 ['review.funny', 'FLOAT', 345.0, -1.0, 0.16539625, 0.0, 0.0, None, None],
 ['review.cool', 'FLOAT', 404.0, -1.0, 0.2703995, 0.0, 0.0, None, None],
 ['review.likes', 'INT', 150, 0, 88.45828825, 102.0, 102, None, None],
 ['review.dislikes', 'INT', 48, 0, 29.02723875, 31.0, 30, None, None],
 ['review.views', 'INT', 20, 0, 10.33045175, 11.0, 2, None, None],
 ['review.reads', 'BOOL', None, None, None, None, None, 70.53295, 29.46705]]

In [161]:
df_1

,review_id,stars,useful,funny,cool,likes,dislikes,views,reads,text,feature
0,KU_O5udG6zpxOg-VcAEodg,3.0,0.0,0.0,0.0,26,23,2,False,"If you decide to eat here, just be aware it is...","[0.41245171427726746, 0.1637980341911316, -0.2..."
1,saUsX_uimxRlCVr67Z4Jig,3.0,0.0,0.0,0.0,40,20,2,True,Family diner. Had the buffet. Eclectic assortm...,"[0.6022008061408997, 0.22512154281139374, 0.06..."
2,AqPFMleE6RsU23_auESxiA,5.0,1.0,0.0,1.0,138,46,15,True,"Wow! Yummy, different, delicious. Our favo...","[0.42374685406684875, 0.2453002780675888, 0.05..."
3,JrIxlS1TzJ-iCu79ul40cQ,1.0,1.0,2.0,1.0,17,12,0,False,I am a long term frequent customer of this est...,"[0.5036842226982117, 0.386075496673584, -0.108..."
4,_ZeMknuYdlQcUqng_Im3yg,5.0,2.0,0.0,0.0,114,42,14,True,Amazingly amazing wings and homemade bleu chee...,"[0.6822971701622009, 0.24157120287418365, 0.05..."
...,...,...,...,...,...,...,...,...,...,...,...
3999995,k3UycIKJVeppV64Ar2IDFg,4.0,0.0,0.0,0.0,77,26,7,True,Nice courtyard with surprisingly good food for...,"[0.5556442737579346, 0.2639174461364746, -0.03..."
3999996,SXkQl5rLAwStkXwUJzZcQw,4.0,0.0,0.0,0.0,72,26,10,False,It was my first time eating there. The food an...,"[0.5749701857566833, 0.36599236726760864, -0.0..."
3999997,jMC9vtsNE_6WM1xqREZNJA,5.0,0.0,0.0,0.0,123,42,13,True,This place warms your heart! Throw-back atmos...,"[0.5249049067497253, 0.26615262031555176, 0.07..."
3999998,hsKomrRKPlQiAJ4sMjRYIg,5.0,1.0,1.0,0.0,96,45,15,True,I love everything about this place! It's smal...,"[0.753829836845398, 0.16873358190059662, -0.05..."
3999999,MHoxwBwmNHNUDU309QhQbQ,5.0,0.0,2.0,1.0,132,40,18,True,The lady who was my server was amazing! I had...,"[0.24697978794574738, 0.5245411396026611, -0.1..."

### tip

In [69]:
base_directory = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip'
base_filename = 'part_'
file_extension = '.csv'

In [70]:
dfs = []

# 使用循环读取part_1.csv到part_10.csv文件
for i in range(1, 10):  # 从1到9，包含9
    file_name = f"{base_filename}{i}{file_extension}"  # 构建文件名
    file_path = os.path.join(base_directory, file_name)  # 构建完整的文件路径
    df = pd.read_csv(file_path)  # 读取CSV文件
    dfs.append(df)  # 将DataFrame添加到列表中

In [71]:
df_2 = pd.concat(dfs, ignore_index=True)

In [73]:
result_3_compliment_sd = getNumColStatisticalData(df_2["compliment"],"INT")

In [75]:
result_3_amount_sd = getNumColStatisticalData(df_2["amount"],"FLOAT")

In [76]:
result_3_num_sd = getNumColStatisticalData(df_2["num"],"INT")

In [115]:
tip_finally = [
    ["tip.compliment"]+result_3_compliment_sd+[None] * 2,
    ["tip.amount"]+result_3_amount_sd+[None] * 2,
    ["tip.num"]+result_3_num_sd+[None] * 2,
]

In [153]:
# 假设df是你的DataFrame
value_counts = df_2["amount"].value_counts()

# 过滤掉计数小于10的数据，并将结果转换为DataFrame
filtered_counts = value_counts[value_counts >= 10].sort_index()

# 重命名索引为'name'，并将计数转换为字符串格式
result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})

# 转换为字典列表，每个字典代表一个记录
formatted_result = result_df.to_dict('records')

# 输出结果
print(formatted_result)

[{'name': 2.0, 'num': '2340'}, {'name': 2.1, 'num': '4800'}, {'name': 2.2, 'num': '4600'}, {'name': 2.3, 'num': '4641'}, {'name': 2.4, 'num': '4841'}, {'name': 2.5, 'num': '4709'}, {'name': 2.6, 'num': '4694'}, {'name': 2.7, 'num': '4715'}, {'name': 2.8, 'num': '4755'}, {'name': 2.9, 'num': '4756'}, {'name': 3.0, 'num': '4652'}, {'name': 3.1, 'num': '4772'}, {'name': 3.2, 'num': '4662'}, {'name': 3.3, 'num': '4702'}, {'name': 3.4, 'num': '4779'}, {'name': 3.5, 'num': '4610'}, {'name': 3.6, 'num': '4834'}, {'name': 3.7, 'num': '4794'}, {'name': 3.8, 'num': '4871'}, {'name': 3.9, 'num': '4809'}, {'name': 4.0, 'num': '4766'}, {'name': 4.1, 'num': '4689'}, {'name': 4.2, 'num': '4816'}, {'name': 4.3, 'num': '4703'}, {'name': 4.4, 'num': '4718'}, {'name': 4.5, 'num': '4784'}, {'name': 4.6, 'num': '4737'}, {'name': 4.7, 'num': '4767'}, {'name': 4.8, 'num': '4700'}, {'name': 4.9, 'num': '4746'}, {'name': 5.0, 'num': '4806'}, {'name': 5.1, 'num': '4635'}, {'name': 5.2, 'num': '4754'}, {'name': 5.3, 'num': '4618'}, {'name': 5.4, 'num': '4765'}, {'name': 5.5, 'num': '4721'}, {'name': 5.6, 'num': '4802'}, {'name': 5.7, 'num': '4760'}, {'name': 5.8, 'num': '4727'}, {'name': 5.9, 'num': '4830'}, {'name': 6.0, 'num': '4756'}, {'name': 6.1, 'num': '4770'}, {'name': 6.2, 'num': '4772'}, {'name': 6.3, 'num': '4567'}, {'name': 6.4, 'num': '4632'}, {'name': 6.5, 'num': '4593'}, {'name': 6.6, 'num': '4650'}, {'name': 6.7, 'num': '4743'}, {'name': 6.8, 'num': '4802'}, {'name': 6.9, 'num': '4762'}, {'name': 7.0, 'num': '4791'}, {'name': 7.1, 'num': '4749'}, {'name': 7.2, 'num': '4632'}, {'name': 7.3, 'num': '4715'}, {'name': 7.4, 'num': '4812'}, {'name': 7.5, 'num': '4828'}, {'name': 7.6, 'num': '4688'}, {'name': 7.7, 'num': '4617'}, {'name': 7.8, 'num': '4715'}, {'name': 7.9, 'num': '4774'}, {'name': 8.0, 'num': '4843'}, {'name': 8.1, 'num': '4660'}, {'name': 8.2, 'num': '4792'}, {'name': 8.3, 'num': '4717'}, {'name': 8.4, 'num': '4595'}, {'name': 8.5, 'num': '4798'}, {'name': 8.6, 'num': '4799'}, {'name': 8.7, 'num': '4751'}, {'name': 8.8, 'num': '4608'}, {'name': 8.9, 'num': '4674'}, {'name': 9.0, 'num': '4602'}, {'name': 9.1, 'num': '4853'}, {'name': 9.2, 'num': '4835'}, {'name': 9.3, 'num': '4861'}, {'name': 9.4, 'num': '4750'}, {'name': 9.5, 'num': '4802'}, {'name': 9.6, 'num': '4658'}, {'name': 9.7, 'num': '4661'}, {'name': 9.8, 'num': '4742'}, {'name': 9.9, 'num': '4728'}, {'name': 10.0, 'num': '4637'}, {'name': 10.1, 'num': '4735'}, {'name': 10.2, 'num': '4865'}, {'name': 10.3, 'num': '4684'}, {'name': 10.4, 'num': '4722'}, {'name': 10.5, 'num': '4672'}, {'name': 10.6, 'num': '4646'}, {'name': 10.7, 'num': '4834'}, {'name': 10.8, 'num': '4755'}, {'name': 10.9, 'num': '4711'}, {'name': 11.0, 'num': '4656'}, {'name': 11.1, 'num': '4730'}, {'name': 11.2, 'num': '4805'}, {'name': 11.3, 'num': '4688'}, {'name': 11.4, 'num': '4756'}, {'name': 11.5, 'num': '4681'}, {'name': 11.6, 'num': '4675'}, {'name': 11.7, 'num': '4668'}, {'name': 11.8, 'num': '4711'}, {'name': 11.9, 'num': '4837'}, {'name': 12.0, 'num': '4740'}, {'name': 12.1, 'num': '4647'}, {'name': 12.2, 'num': '4678'}, {'name': 12.3, 'num': '4772'}, {'name': 12.4, 'num': '4597'}, {'name': 12.5, 'num': '4755'}, {'name': 12.6, 'num': '4600'}, {'name': 12.7, 'num': '4773'}, {'name': 12.8, 'num': '4749'}, {'name': 12.9, 'num': '4687'}, {'name': 13.0, 'num': '4711'}, {'name': 13.1, 'num': '4716'}, {'name': 13.2, 'num': '4725'}, {'name': 13.3, 'num': '4879'}, {'name': 13.4, 'num': '4685'}, {'name': 13.5, 'num': '4706'}, {'name': 13.6, 'num': '4647'}, {'name': 13.7, 'num': '4719'}, {'name': 13.8, 'num': '4651'}, {'name': 13.9, 'num': '4723'}, {'name': 14.0, 'num': '4674'}, {'name': 14.1, 'num': '4672'}, {'name': 14.2, 'num': '4740'}, {'name': 14.3, 'num': '4802'}, {'name': 14.4, 'num': '4732'}, {'name': 14.5, 'num': '4584'}, {'name': 14.6, 'num': '4888'}, {'name': 14.7, 'num': '4615'}, {'name': 14.8, 'num': '4811'}, {'name': 14.9, 'num': '4708'}, {'name': 15.0, 'num': '4621'}, {'name': 15.1, 'num': '4689'}, {'name': 15.2, 'num': '4632'}, {'name': 15.3, 'num': '4832'}, {'name': 15.4, 'num': '4649'}, {'name': 15.5, 'num': '4664'}, {'name': 15.6, 'num': '4729'}, {'name': 15.7, 'num': '4762'}, {'name': 15.8, 'num': '4773'}, {'name': 15.9, 'num': '4823'}, {'name': 16.0, 'num': '4890'}, {'name': 16.1, 'num': '4788'}, {'name': 16.2, 'num': '4660'}, {'name': 16.3, 'num': '4744'}, {'name': 16.4, 'num': '4780'}, {'name': 16.5, 'num': '4678'}, {'name': 16.6, 'num': '4634'}, {'name': 16.7, 'num': '4817'}, {'name': 16.8, 'num': '4863'}, {'name': 16.9, 'num': '4728'}, {'name': 17.0, 'num': '4751'}, {'name': 17.1, 'num': '4703'}, {'name': 17.2, 'num': '4771'}, {'name': 17.3, 'num': '4619'}, {'name': 17.4, 'num': '4742'}, {'name': 17.5, 'num': '4702'}, {'name': 17.6, 'num': '4809'}, {'name': 17.7, 'num': '4723'}, {'name': 17.8, 'num': '4701'}, {'name': 17.9, 'num': '4764'}, {'name': 18.0, 'num': '4752'}, {'name': 18.1, 'num': '4946'}, {'name': 18.2, 'num': '4791'}, {'name': 18.3, 'num': '4725'}, {'name': 18.4, 'num': '4684'}, {'name': 18.5, 'num': '4807'}, {'name': 18.6, 'num': '4644'}, {'name': 18.7, 'num': '4634'}, {'name': 18.8, 'num': '4600'}, {'name': 18.9, 'num': '4680'}, {'name': 19.0, 'num': '4588'}, {'name': 19.1, 'num': '4702'}, {'name': 19.2, 'num': '4759'}, {'name': 19.3, 'num': '4794'}, {'name': 19.4, 'num': '4661'}, {'name': 19.5, 'num': '4737'}, {'name': 19.6, 'num': '4794'}, {'name': 19.7, 'num': '4794'}, {'name': 19.8, 'num': '4706'}, {'name': 19.9, 'num': '4670'}, {'name': 20.0, 'num': '2393'}]

In [152]:
df_2

,user_id,business_id,compliment,amount,num,text,feature
0,rCumu_NyXfbyq16cP8vOEw,cXSyVvOr9YRN9diDkaWs0Q,0,14.9,1,Simply the best breakfast around!! The staff i...,"[0.6405475735664368, 0.17660640180110931, 0.06..."
1,LT_JU6bY75H918eKnnXeVQ,kLYhipAEvdT1ORfluX5gbw,0,2.2,1,Crunchy French toast is amazing!,"[0.25802168250083923, 0.15587060153484344, 0.1..."
2,sxZX1armKzagQxDnbvPnkw,gTC8IQ_i8zXytWSly3Ttvg,0,11.6,1,"Lunch specials are great, especially their hom...","[0.36990439891815186, 0.017034143209457397, 0...."
3,KI4UutWtai0UKZ6ZK2pg2Q,P3bw4h4kCaMaYqGGNLt3Jg,0,17.4,1,"Low selection, quiet","[0.417603075504303, 0.23099857568740845, 0.317..."
4,C14KW1jjKM8QlYfMyzP1sQ,aUjJ_x1KuvWmqIErhdaHzg,0,4.4,1,"Pretty good pad thai, but when I asked for lim...","[0.5951403975486755, 0.2372429370880127, -0.10..."
...,...,...,...,...,...,...,...
851028,vbQVYwb245MCFhqxg9aSng,7_5gXg2aG_wrJ18wdkDymQ,0,8.4,1,Great local spot with delicious food and live ...,"[0.44298797845840454, 0.13415025174617767, -0...."
851029,u8awpvumycJ6nR6Dn5tohQ,NHJa__j-wYQkwlaYWGz4Xg,0,6.6,1,Went above and beyond!,"[0.5153499245643616, 0.11985791474580765, 0.22..."
851030,tXOUDSVa51nJrX2ip9PdpA,13M0Y9AqznYGihb0zdIOlA,0,15.9,1,Amazing service!! I'm and out in no time! Beat...,"[0.32804355025291443, 0.4703589975833893, 0.03..."
851031,zD5pAdi4PDU1D1dO3c56lA,6P7MthfuntKbl2ZE2CCbAQ,0,6.2,1,Great service and beautiful nails!! Love my na...,"[0.3359599709510803, 0.23242567479610443, 0.06..."
851032,giQSReOdlfwPd9dND2FvDg,Qji91RHuT2pznRmv_CUYJQ,0,7.2,1,Donation drop off hours (non-clothing items - ...,"[0.4545551836490631, 0.09608332812786102, 0.16..."

### problem

In [77]:
df_3 = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/mooccubex/csv/problem/problem.csv')

In [155]:
converted = pd.to_numeric(df_3['id'], errors='coerce')

In [80]:
chinese_count = df_3['language'].value_counts()['Chinese']
english_count = df_3['language'].value_counts()['English']
total_count = len(df_3)

chinese_percentage = (chinese_count / total_count) * 100
english_percentage = (english_count / total_count) * 100

# 输出结果
print(f"Chinese的占比: {chinese_percentage:.2f}%")
print(f"English的占比: {english_percentage:.2f}%")

Chinese的占比: 89.46%
English的占比: 10.54%

In [81]:
result_4_language_sd=["BOOL",chinese_percentage,english_percentage]

In [82]:
result_4_language_sd

['BOOL', 89.4644494955537, 10.535550504446306]

In [85]:
result_4_score_sd = getValueCountsStatisticalData(getValusCounts(df_3,"score",0),"VARCHAR")

In [86]:
result_4_type_sd = getValueCountsStatisticalData(getValusCounts(df_3,"type",0),"VARCHAR")

In [135]:
problem_finally = [
    ["problem.language"] +[result_4_language_sd[0]] +[None] * 5+result_4_language_sd[1:3],
    ["problem.score"]+result_4_score_sd+[None] * 2,
    ["problem.type"]+result_4_type_sd+[None] * 2   
]

In [160]:
df_3

,id,language,content,score,type,typetext,feature
0,13816,Chinese,中国共产党从成立之日起，就确立了（ ）的远大理想，始终团结带领中国人民朝着这个伟大目标前进。,1.0,1,单选题,"[0.3620103895664215, 0.4917919635772705, 0.001..."
1,13817,Chinese,走好新时代的长征路，大学生要不断增强中国特色社会主义（ ），自觉做共产主义远大理想和中国特色...,1.0,1,单选题,"[0.307481974363327, 0.13994258642196655, 0.536..."
2,13829,Chinese,国家安全问题事关国家安危和民族存亡，大学生要增强国家安全意识，以下做法错误的是（ ）,1.0,1,单选题,"[-0.15822555124759674, -0.12112200260162354, -..."
3,13832,Chinese,对于社会主义核心价值观的自信，来自于（ ）,2.0,2,多选题,"[0.06346714496612549, -0.10366339236497879, 0...."
4,13835,Chinese,党的十八大提出，要倡导（ ），倡导（ ），倡导（ ），积极培育和践行社会主义核心价值观。,1.0,1,单选题,"[0.07375973463058472, 0.32700297236442566, -0...."
...,...,...,...,...,...,...,...
125380,8420963,English,The endorsor of of Insurance Policy is Shangha...,2.0,6,判断题,"[0.1462920755147934, 0.26734307408332825, 0.09..."
125381,8420964,English,CREDIT NUMBER AND NAME OF ISSUING BANK are no ...,2.0,6,判断题,"[0.09381052106618881, 0.00038472795858979225, ..."
125382,8420965,English,The Bill of Lading must be endorsed in blank b...,2.0,6,判断题,"[0.08344624936580658, 0.11163408309221268, -0...."
125383,8420966,English,The goods description of goods in the Bill of ...,2.0,6,判断题,"[0.3675398528575897, -0.18399843573570251, 0.3..."
125384,8420967,English,"In FOB transaction, unless otherwise stipulate...",2.0,1,单选题,"[0.13209886848926544, 0.05838692933320999, 0.1..."

### total

In [138]:
total = business_finally + review_finally + tip_finally + problem_finally

In [148]:
list = [["column","type","max","min","avg","medin","mode","true_precentage","false_precentage"]] + total

In [149]:
df_metadata = pd.DataFrame(list[1:], columns=list[0])

In [151]:
df_metadata.to_csv("/remote-home/cs_acmis_wsf/ai4dingo/data/metadata.csv", index=False)

In [150]:
df_metadata

,column,type,max,min,avg,medin,mode,true_precentage,false_precentage
0,business.city,VARCHAR,14560.0,86.0,642.245370,210.5,86.0,NaN,NaN
1,business.state,VARCHAR,34013.0,1.0,5564.555556,2144.0,1.0,NaN,NaN
2,business.stars,FLOAT,5.0,1.0,3.597682,3.5,4.0,NaN,NaN
3,business.review,INT,7568.0,5.0,44.892874,15.0,5.0,NaN,NaN
4,business.favorites,INT,220.0,0.0,108.518420,111.0,20.0,NaN,NaN
5,business.avgspend,INT,160.0,10.0,64.451016,55.0,20.0,NaN,NaN
6,business.popular,BOOL,NaN,NaN,NaN,NaN,NaN,67.042059,32.957941
7,review.starts,FLOAT,5.0,1.0,3.955599,5.0,5.0,NaN,NaN
8,review.useful,FLOAT,404.0,-1.0,0.678382,0.0,0.0,NaN,NaN
9,review.funny,FLOAT,345.0,-1.0,0.165396,0.0,0.0,NaN,NaN
10,review.cool,FLOAT,404.0,-1.0,0.270400,0.0,0.0,NaN,NaN
11,review.likes,INT,150.0,0.0,88.458288,102.0,102.0,NaN,NaN
12,review.dislikes,INT,48.0,0.0,29.027239,31.0,30.0,NaN,NaN
13,review.views,INT,20.0,0.0,10.330452,11.0,2.0,NaN,NaN
14,review.reads,BOOL,NaN,NaN,NaN,NaN,NaN,70.532950,29.467050
15,tip.compliment,INT,6.0,0.0,0.012998,0.0,0.0,NaN,NaN
16,tip.amount,FLOAT,20.0,2.0,10.997566,11.0,18.1,NaN,NaN
17,tip.num,INT,213.0,1.0,1.452616,1.0,1.0,NaN,NaN
18,problem.language,BOOL,NaN,NaN,NaN,NaN,NaN,89.464449,10.535551
19,problem.score,VARCHAR,94453.0,1.0,3299.605263,37.0,1.0,NaN,NaN
20,problem.type,VARCHAR,69088.0,6.0,17912.142857,3725.0,6.0,NaN,NaN