In [2]:
import pandas as pd
import random
import numpy as np
from sklearn.model_selection import train_test_split
import json

### common

In [6]:
def getValueCounts(df, col, val):
    value_counts = df[col].value_counts()
    filtered_counts = value_counts[value_counts >= val].sort_index()
    result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})
    formatted_result = result_df.to_dict('records')
    print(len(formatted_result))
    print(formatted_result)

### Movie

In [3]:
movie_df = pd.read_csv('F:\\moviedata-10m\\电影数据集-CSV格式\\movies.csv')

In [5]:
movie_df = movie_df.drop(['ALIAS','ACTORS','COVER','DIRECTORS','GENRES','IMDB_ID','OFFICIAL_SITE','STORYLINE','SLUG','ACTOR_IDS','DIRECTOR_IDS'],axis=1)

In [7]:
movie_df = movie_df.drop(['RELEASE_DATE','TAGS'],axis=1)

In [9]:
movie_df = movie_df.dropna()

In [17]:
def handle_language(x):
    x = str(x)
    return x.split("/")[0]

In [18]:
movie_df["LANGUAGES"] = movie_df["LANGUAGES"].apply(handle_language)

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\4101539447.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_df["LANGUAGES"] = movie_df["LANGUAGES"].apply(handle_language)

In [20]:
movie_df["REGIONS"] = movie_df["REGIONS"].apply(handle_language)

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\670504348.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_df["REGIONS"] = movie_df["REGIONS"].apply(handle_language)

In [27]:
 movie_df["YEAR"] = movie_df["YEAR"].astype(int)

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\597009075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_df["YEAR"] = movie_df["YEAR"].astype(int)

In [30]:
 movie_df["DOUBAN_VOTES"] = movie_df["DOUBAN_VOTES"].astype(int)

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\2222367619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_df["DOUBAN_VOTES"] = movie_df["DOUBAN_VOTES"].astype(int)

In [54]:
movie_df = movie_df.rename(columns={'MOVIE_ID': 'movie_id', 'NAME': 'name','DOUBAN_SCORE':"socre","LANGUAGES":"language","MINS":"mins","REGIONS":"region","YEAR":"year"})

In [56]:
movie_df = movie_df.rename(columns={'DOUBAN_VOTES': 'vote'})

In [57]:
movie_df

,movie_id,name,socre,vote,language,mins,region,year
0,26670818,情定河州,0.0,0,汉语普通话,0.0,中国大陆,2049
1,25815002,我不是李小龙,0.0,0,汉语普通话,0.0,中国大陆,2049
2,26392287,曼哈顿中国女孩,0.0,0,英语,0.0,中国大陆,2049
3,26695995,绿毛水怪,0.0,0,汉语普通话,0.0,中国大陆,2049
4,26392292,为了祖国,0.0,0,汉语普通话,0.0,中国大陆,2049
...,...,...,...,...,...,...,...,...
140494,5108157,Longe da Vista - 电影,0.0,0,葡萄牙语,87.0,葡萄牙,1998
140496,5108126,Phera - 电影,0.0,0,Bengali,94.0,印度,1988
140499,5108078,Fast Track - 电影,0.0,0,英语,60.0,美国,1997
140500,5108060,7-9-13 - 电影,0.0,0,丹麦语,0.0,丹麦,1934
140501,1291545,大鱼 - 电影,0.0,346019,英语,125.0,美国,2003

In [58]:
movie_df.to_csv('F:\\LCE\\dataset\\douban\\movies.csv', index=False)

In [3]:
df =  pd.read_csv('F:\\LCE\\dataset\\douban\\movies.csv')

In [4]:
df

,movie_id,name,socre,vote,language,mins,region,year
0,26670818,情定河州,0.0,0,汉语普通话,0.0,中国大陆,2049
1,25815002,我不是李小龙,0.0,0,汉语普通话,0.0,中国大陆,2049
2,26392287,曼哈顿中国女孩,0.0,0,英语,0.0,中国大陆,2049
3,26695995,绿毛水怪,0.0,0,汉语普通话,0.0,中国大陆,2049
4,26392292,为了祖国,0.0,0,汉语普通话,0.0,中国大陆,2049
...,...,...,...,...,...,...,...,...
131437,5108157,Longe da Vista - 电影,0.0,0,葡萄牙语,87.0,葡萄牙,1998
131438,5108126,Phera - 电影,0.0,0,Bengali,94.0,印度,1988
131439,5108078,Fast Track - 电影,0.0,0,英语,60.0,美国,1997
131440,5108060,7-9-13 - 电影,0.0,0,丹麦语,0.0,丹麦,1934
131441,1291545,大鱼 - 电影,0.0,346019,英语,125.0,美国,2003

In [4]:
df['language'] = df['language'].apply(lambda x: x.strip() if isinstance(x, str) else x)

In [5]:
df['region'] = df['region'].apply(lambda x: x.strip() if isinstance(x, str) else x)

In [9]:
getValueCounts(df,'mins',50)

146
[{'name': 0.0, 'num': '39993'}, {'name': 5.0, 'num': '81'}, {'name': 6.0, 'num': '76'}, {'name': 7.0, 'num': '102'}, {'name': 8.0, 'num': '78'}, {'name': 9.0, 'num': '56'}, {'name': 10.0, 'num': '136'}, {'name': 11.0, 'num': '75'}, {'name': 12.0, 'num': '87'}, {'name': 13.0, 'num': '66'}, {'name': 14.0, 'num': '80'}, {'name': 15.0, 'num': '107'}, {'name': 16.0, 'num': '79'}, {'name': 17.0, 'num': '56'}, {'name': 18.0, 'num': '75'}, {'name': 20.0, 'num': '119'}, {'name': 21.0, 'num': '68'}, {'name': 22.0, 'num': '98'}, {'name': 23.0, 'num': '83'}, {'name': 24.0, 'num': '208'}, {'name': 25.0, 'num': '215'}, {'name': 26.0, 'num': '74'}, {'name': 27.0, 'num': '58'}, {'name': 28.0, 'num': '74'}, {'name': 29.0, 'num': '56'}, {'name': 30.0, 'num': '300'}, {'name': 40.0, 'num': '90'}, {'name': 44.0, 'num': '57'}, {'name': 45.0, 'num': '235'}, {'name': 46.0, 'num': '72'}, {'name': 47.0, 'num': '75'}, {'name': 48.0, 'num': '105'}, {'name': 49.0, 'num': '64'}, {'name': 50.0, 'num': '424'}, {'name': 51.0, 'num': '80'}, {'name': 52.0, 'num': '118'}, {'name': 53.0, 'num': '105'}, {'name': 54.0, 'num': '135'}, {'name': 55.0, 'num': '191'}, {'name': 56.0, 'num': '152'}, {'name': 57.0, 'num': '147'}, {'name': 58.0, 'num': '218'}, {'name': 59.0, 'num': '180'}, {'name': 60.0, 'num': '1172'}, {'name': 61.0, 'num': '310'}, {'name': 62.0, 'num': '377'}, {'name': 63.0, 'num': '396'}, {'name': 64.0, 'num': '326'}, {'name': 65.0, 'num': '526'}, {'name': 66.0, 'num': '325'}, {'name': 67.0, 'num': '356'}, {'name': 68.0, 'num': '380'}, {'name': 69.0, 'num': '333'}, {'name': 70.0, 'num': '1047'}, {'name': 71.0, 'num': '472'}, {'name': 72.0, 'num': '613'}, {'name': 73.0, 'num': '565'}, {'name': 74.0, 'num': '618'}, {'name': 75.0, 'num': '1058'}, {'name': 76.0, 'num': '569'}, {'name': 77.0, 'num': '628'}, {'name': 78.0, 'num': '755'}, {'name': 79.0, 'num': '608'}, {'name': 80.0, 'num': '1950'}, {'name': 81.0, 'num': '872'}, {'name': 82.0, 'num': '1269'}, {'name': 83.0, 'num': '1280'}, {'name': 84.0, 'num': '1387'}, {'name': 85.0, 'num': '2461'}, {'name': 86.0, 'num': '1787'}, {'name': 87.0, 'num': '1889'}, {'name': 88.0, 'num': '2300'}, {'name': 89.0, 'num': '2092'}, {'name': 90.0, 'num': '7214'}, {'name': 91.0, 'num': '2137'}, {'name': 92.0, 'num': '2532'}, {'name': 93.0, 'num': '2526'}, {'name': 94.0, 'num': '2157'}, {'name': 95.0, 'num': '3375'}, {'name': 96.0, 'num': '2119'}, {'name': 97.0, 'num': '1859'}, {'name': 98.0, 'num': '1957'}, {'name': 99.0, 'num': '1355'}, {'name': 100.0, 'num': '3420'}, {'name': 101.0, 'num': '1206'}, {'name': 102.0, 'num': '1409'}, {'name': 103.0, 'num': '1207'}, {'name': 104.0, 'num': '1198'}, {'name': 105.0, 'num': '1863'}, {'name': 106.0, 'num': '1052'}, {'name': 107.0, 'num': '1055'}, {'name': 108.0, 'num': '1041'}, {'name': 109.0, 'num': '729'}, {'name': 110.0, 'num': '1591'}, {'name': 111.0, 'num': '616'}, {'name': 112.0, 'num': '739'}, {'name': 113.0, 'num': '614'}, {'name': 114.0, 'num': '564'}, {'name': 115.0, 'num': '806'}, {'name': 116.0, 'num': '498'}, {'name': 117.0, 'num': '509'}, {'name': 118.0, 'num': '544'}, {'name': 119.0, 'num': '412'}, {'name': 120.0, 'num': '1238'}, {'name': 121.0, 'num': '308'}, {'name': 122.0, 'num': '320'}, {'name': 123.0, 'num': '310'}, {'name': 124.0, 'num': '331'}, {'name': 125.0, 'num': '374'}, {'name': 126.0, 'num': '244'}, {'name': 127.0, 'num': '234'}, {'name': 128.0, 'num': '268'}, {'name': 129.0, 'num': '187'}, {'name': 130.0, 'num': '343'}, {'name': 131.0, 'num': '153'}, {'name': 132.0, 'num': '181'}, {'name': 133.0, 'num': '161'}, {'name': 134.0, 'num': '164'}, {'name': 135.0, 'num': '234'}, {'name': 136.0, 'num': '120'}, {'name': 137.0, 'num': '138'}, {'name': 138.0, 'num': '145'}, {'name': 139.0, 'num': '119'}, {'name': 140.0, 'num': '223'}, {'name': 141.0, 'num': '85'}, {'name': 142.0, 'num': '102'}, {'name': 143.0, 'num': '100'}, {'name': 144.0, 'num': '88'}, {'name': 145.0, 'num': '106'}, {'name': 146.0, 'num': '58'}, {'name': 147.0, 'num': '68'}, {'name': 148.0, 'num': '79'}, {'name': 150.0, 'num': '232'}, {'name': 151.0, 'num': '53'}, {'name': 152.0, 'num': '69'}, {'name': 153.0, 'num': '53'}, {'name': 154.0, 'num': '50'}, {'name': 155.0, 'num': '85'}, {'name': 157.0, 'num': '61'}, {'name': 158.0, 'num': '51'}, {'name': 160.0, 'num': '122'}, {'name': 162.0, 'num': '51'}, {'name': 165.0, 'num': '62'}, {'name': 170.0, 'num': '86'}, {'name': 180.0, 'num': '170'}, {'name': 200.0, 'num': '53'}]

In [13]:
df.to_csv('F:\\LCE\\dataset\\douban\\movies.csv', index=False)

### Comment

In [70]:
comment_df = pd.read_csv('F:\\moviedata-10m\\电影数据集-CSV格式\\comments.csv')

In [72]:
comment_df = comment_df.drop(['USER_MD5','MOVIE_ID','CONTENT'], axis=1)

In [75]:
comment_df = comment_df.rename(columns={'COMMENT_ID':'comment_id',"VOTES":"vote","COMMENT_TIME":"comment_time","RATING":"rating"})

In [77]:
comment_df = comment_df.dropna()

In [80]:
comment_df["comment_time"] = pd.to_datetime(comment_df['comment_time'])

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\3262402991.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comment_df["comment_time"] = pd.to_datetime(comment_df['comment_time'])

In [82]:
comment_df["year"] = comment_df['comment_time'].dt.year

C:\Users\wushengfa\AppData\Local\Temp\ipykernel_1376\3985401395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comment_df["year"] = comment_df['comment_time'].dt.year

In [84]:
comment_df = comment_df.drop(["comment_time"], axis=1)

In [85]:
comment_df

         comment_id  vote  rating  year
0        1359352573     0     2.0  2018
1        1598245094     0     1.0  2019
2         311937819     0     3.0  2010
5         457663846     0     4.0  2011
6         313277849     0     4.0  2010
...             ...   ...     ...   ...
4428470  1402192514     0     5.0  2018
4428471  1131394883     0     4.0  2017
4428472  1565118781     0     3.0  2018
4428473  1888955067     0     4.0  2019
4428474  1168001819     0     3.0  2017

[4166705 rows x 4 columns]

In [86]:
comment_df.to_csv('F:\\LCE\\dataset\\douban\\comments.csv', index=False)

In [97]:
getValueCounts(comment_df,'year',5)

15
[{'name': 2005, 'num': '1414'}, {'name': 2006, 'num': '12293'}, {'name': 2007, 'num': '30894'}, {'name': 2008, 'num': '84363'}, {'name': 2009, 'num': '131915'}, {'name': 2010, 'num': '244088'}, {'name': 2011, 'num': '332631'}, {'name': 2012, 'num': '350967'}, {'name': 2013, 'num': '290515'}, {'name': 2014, 'num': '251910'}, {'name': 2015, 'num': '251373'}, {'name': 2016, 'num': '324832'}, {'name': 2017, 'num': '428703'}, {'name': 2018, 'num': '532375'}, {'name': 2019, 'num': '898432'}]