In [24]:
import pandas as pd
import os
import random

In [2]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review.csv')

/tmp/ipykernel_159971/4232273744.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/review.csv')

In [3]:
df

,review_id,user_id,business_id,stars,useful,funny,cool,text,review_data,length,feature
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,511.0,"[0.41245171427726746, 0.1637980341911316, -0.2..."
1,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30,339.0,"[0.6022008061408997, 0.22512154281139374, 0.06..."
2,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03,243.0,"[0.42374685406684875, 0.2453002780675888, 0.05..."
3,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,2015-09-23 23:10:31,341.0,"[0.5036842226982117, 0.386075496673584, -0.108..."
4,_ZeMknuYdlQcUqng_Im3yg,yfFzsLmaWF2d4Sr0UNbBgg,LHSTtnW3YHCeUkRDGyJOyw,5.0,2.0,0.0,0.0,Amazingly amazing wings and homemade bleu chee...,2015-08-07 02:29:16,192.0,"[0.6822971701622009, 0.24157120287418365, 0.05..."
...,...,...,...,...,...,...,...,...,...,...,...
4237582,wD5ZWao_vjyT2h4xmGam8Q,7L7GL5Pi2cf8mbm2Dpw4zw,e_E-jq9mwm7wk75k7Yi-Xw,5.0,1.0,0.0,1.0,It is very rare for a restaurant to be this go...,2022-01-17 22:36:01,336.0,"[0.42925330996513367, 0.36743032932281494, -0...."
4237583,zHZ-A1qyKDEgyZMDaD--wg,_XVdmFWSgTN6YlojUxixTA,6WaI-IN8ql0xpEKlb4q8tg,5.0,1.0,0.0,0.0,We redesigned my moms dress and mad it complet...,2022-01-17 20:59:01,209.0,"[0.30092892050743103, 0.3077335059642792, -0.2..."
4237584,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5.0,1.0,2.0,1.0,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20,320.0,"[0.5364809632301331, 0.04880490154027939, -0.2..."
4237585,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5.0,2.0,1.0,2.0,"This spot offers a great, affordable east week...",2021-03-31 16:55:10,395.0,"[0.6214404106140137, 0.25845226645469666, -0.0..."
4237586,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4.0,1.0,0.0,0.0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30,463.0,"[0.8896353244781494, 0.15281465649604797, 0.28..."

In [5]:
invalid_indices = []

# 尝试将'stars'列转换为float类型，并捕获异常
for index, value in df['stars'].items():  # 使用.items()替代.iteritems()
    try:
        _ = float(value)  # 尝试转换为float
    except ValueError:
        invalid_indices.append(index)  # 如果转换失败，添加索引到列表

# 打印无法转换的行索引
print("无法转换为float的行索引:", invalid_indices)

无法转换为float的行索引: [13907, 420989, 484477, 892115, 1367869, 1608549, 1743729, 2136455, 2358787, 2488056, 2633403, 2955014, 2970972, 3392140, 3407206, 3409581]

In [6]:
# 使用drop方法删除invalid_indices中的行
df.drop(invalid_indices, axis=0, inplace=True)

In [7]:
df = df.reset_index(drop=True)

In [8]:
row_data = df.loc[13907]

In [9]:
row_data

review_id                                 GRkOGW9RRHeUC-WZYgh8AQ
user_id                                   MBvUKfx-Srrza3vQEzxYVg
business_id                               6VQ1UhrwqRPkO1Bt4bbxlg
stars                                                        5.0
useful                                                       1.0
funny                                                        0.0
cool                                                         1.0
text           Love this place! The owner is a nuritionist an...
review_data                                  2016-02-01 05:57:19
length                                                     366.0
feature        [0.5660372972488403, 0.4040418565273285, -0.00...
Name: 13907, dtype: object

In [10]:
df = df.drop('length', axis=1)

In [12]:
df = df.drop('review_data', axis=1)

In [14]:
df = df.drop('user_id', axis=1)

In [15]:
df = df.drop('business_id', axis=1)

In [17]:
null_indices = df[df['feature'].isnull()].index

In [18]:
null_indices

Index([  13906,  420987,  484474,  892110,  892111, 1367862, 1367863, 1367864,
       1608543, 1743722, 2136447, 2358778, 2488045, 2488046, 2633392, 2955001,
       2955002, 2970959, 3392125, 3392126, 3407186, 3407187, 3407188, 3407189,
       3407190, 3407191, 3409565],
      dtype='int64')

In [19]:
df.drop(null_indices, axis=0, inplace=True)

In [20]:
df = df.reset_index(drop=True)

In [50]:
def generate_likes(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(0, 20)
    elif 2 < stars <= 3:
        return random.randint(20, 70)
    elif 3 < stars <= 4:
        return random.randint(70, 120)
    elif 4 < stars <= 5:
        return random.randint(90, 150)
    else:
        return None  # 如果stars的值不在1到5之间，返回None

In [51]:
def generate_dislikes(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(0, 15)
    elif 2 < stars <= 3:
        return random.randint(15, 23)
    elif 3 < stars <= 4:
        return random.randint(23, 30)
    elif 4 < stars <= 5:
        return random.randint(30, 48)
    else:
        return None  # 如果stars的值不在1到5之间，返回None

In [59]:
def generate_views(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(0, 2)
    elif 2 < stars <= 3:
        return random.randint(2, 5)
    elif 3 < stars <= 4:
        return random.randint(5, 11)
    elif 4 < stars <= 5:
        return random.randint(11, 20)
    else:
        return None  # 如果stars的值不在1到5之间，返回None

In [61]:
def generate_reads(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.random() < 0.3
    elif 2 < stars <= 3:
        return random.random() < 0.5
    elif 3 < stars <= 4:
        return random.random() < 0.7
    elif 4 < stars <= 5:
        return  random.random() < 0.88
    else:
        return None  # 如果stars的值不在1到5之间，返回None

In [52]:
df['likes'] = df['stars'].apply(generate_likes)

In [53]:
df['dislikes'] = df['stars'].apply(generate_dislikes)

In [60]:
df['views'] = df['stars'].apply(generate_views)

In [62]:
df['reads'] = df['stars'].apply(generate_reads)

In [63]:
df

,review_id,stars,useful,funny,cool,text,feature,likes,dislikes,views,reads
0,KU_O5udG6zpxOg-VcAEodg,3.0,0.0,0.0,0.0,"If you decide to eat here, just be aware it is...","[0.41245171427726746, 0.1637980341911316, -0.2...",26,23,2,False
1,saUsX_uimxRlCVr67Z4Jig,3.0,0.0,0.0,0.0,Family diner. Had the buffet. Eclectic assortm...,"[0.6022008061408997, 0.22512154281139374, 0.06...",40,20,2,True
2,AqPFMleE6RsU23_auESxiA,5.0,1.0,0.0,1.0,"Wow! Yummy, different, delicious. Our favo...","[0.42374685406684875, 0.2453002780675888, 0.05...",138,46,15,True
3,JrIxlS1TzJ-iCu79ul40cQ,1.0,1.0,2.0,1.0,I am a long term frequent customer of this est...,"[0.5036842226982117, 0.386075496673584, -0.108...",17,12,0,False
4,_ZeMknuYdlQcUqng_Im3yg,5.0,2.0,0.0,0.0,Amazingly amazing wings and homemade bleu chee...,"[0.6822971701622009, 0.24157120287418365, 0.05...",114,42,14,True
...,...,...,...,...,...,...,...,...,...,...,...
4237539,wD5ZWao_vjyT2h4xmGam8Q,5.0,1.0,0.0,1.0,It is very rare for a restaurant to be this go...,"[0.42925330996513367, 0.36743032932281494, -0....",149,45,16,True
4237540,zHZ-A1qyKDEgyZMDaD--wg,5.0,1.0,0.0,0.0,We redesigned my moms dress and mad it complet...,"[0.30092892050743103, 0.3077335059642792, -0.2...",126,47,15,True
4237541,H0RIamZu0B0Ei0P4aeh3sQ,5.0,1.0,2.0,1.0,Latest addition to services from ICCU is Apple...,"[0.5364809632301331, 0.04880490154027939, -0.2...",91,37,14,False
4237542,shTPgbgdwTHSuU67mGCmZQ,5.0,2.0,1.0,2.0,"This spot offers a great, affordable east week...","[0.6214404106140137, 0.25845226645469666, -0.0...",105,45,19,True
4237543,YNfNhgZlaaCO5Q_YJR4rEw,4.0,1.0,0.0,0.0,This Home Depot won me over when I needed to g...,"[0.8896353244781494, 0.15281465649604797, 0.28...",85,23,9,False

In [66]:
df = df[['review_id','stars','useful','funny','cool','likes','dislikes','views','reads','text','feature']]

In [67]:
df

,review_id,stars,useful,funny,cool,likes,dislikes,views,reads,text,feature
0,KU_O5udG6zpxOg-VcAEodg,3.0,0.0,0.0,0.0,26,23,2,False,"If you decide to eat here, just be aware it is...","[0.41245171427726746, 0.1637980341911316, -0.2..."
1,saUsX_uimxRlCVr67Z4Jig,3.0,0.0,0.0,0.0,40,20,2,True,Family diner. Had the buffet. Eclectic assortm...,"[0.6022008061408997, 0.22512154281139374, 0.06..."
2,AqPFMleE6RsU23_auESxiA,5.0,1.0,0.0,1.0,138,46,15,True,"Wow! Yummy, different, delicious. Our favo...","[0.42374685406684875, 0.2453002780675888, 0.05..."
3,JrIxlS1TzJ-iCu79ul40cQ,1.0,1.0,2.0,1.0,17,12,0,False,I am a long term frequent customer of this est...,"[0.5036842226982117, 0.386075496673584, -0.108..."
4,_ZeMknuYdlQcUqng_Im3yg,5.0,2.0,0.0,0.0,114,42,14,True,Amazingly amazing wings and homemade bleu chee...,"[0.6822971701622009, 0.24157120287418365, 0.05..."
...,...,...,...,...,...,...,...,...,...,...,...
4237539,wD5ZWao_vjyT2h4xmGam8Q,5.0,1.0,0.0,1.0,149,45,16,True,It is very rare for a restaurant to be this go...,"[0.42925330996513367, 0.36743032932281494, -0...."
4237540,zHZ-A1qyKDEgyZMDaD--wg,5.0,1.0,0.0,0.0,126,47,15,True,We redesigned my moms dress and mad it complet...,"[0.30092892050743103, 0.3077335059642792, -0.2..."
4237541,H0RIamZu0B0Ei0P4aeh3sQ,5.0,1.0,2.0,1.0,91,37,14,False,Latest addition to services from ICCU is Apple...,"[0.5364809632301331, 0.04880490154027939, -0.2..."
4237542,shTPgbgdwTHSuU67mGCmZQ,5.0,2.0,1.0,2.0,105,45,19,True,"This spot offers a great, affordable east week...","[0.6214404106140137, 0.25845226645469666, -0.0..."
4237543,YNfNhgZlaaCO5Q_YJR4rEw,4.0,1.0,0.0,0.0,85,23,9,False,This Home Depot won me over when I needed to g...,"[0.8896353244781494, 0.15281465649604797, 0.28..."

In [68]:
def split_csv(df, output_folder, row_limit=100000):
    # 确保输出文件夹存在
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # 初始化变量
    count = 1
    split_files = []

    # 分割文件
    for i in range(0, df.shape[0], row_limit):
        # 根据row_limit切分DataFrame
        df_subset = df.iloc[i:i + row_limit]
        
        # 构造输出文件的完整路径
        file_name = os.path.join(output_folder, f"part_{count}.csv")  # 使用4位数的计数器，不足的前面补0
        # 将子集DataFrame存储为CSV文件，不包含索引
        df_subset.to_csv(file_name, index=False)
        
        # 将文件名添加到列表中
        split_files.append(file_name)
        
        # 更新计数器
        count += 1

    # 返回分割文件的列表（可选）
    return split_files

In [69]:
output_folder = "/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review"
split_files = split_csv(df, output_folder)
print("分割的CSV文件列表：", split_files)

分割的CSV文件列表： ['/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_1.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_2.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_3.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_4.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_5.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_6.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_7.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_8.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_9.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_10.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_11.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_12.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_13.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_14.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_15.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_16.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_17.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_18.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_19.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_20.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_21.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_22.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_23.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_24.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_25.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_26.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_27.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_28.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_29.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_30.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_31.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_32.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_33.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_34.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_35.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_36.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_37.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_38.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_39.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_40.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_41.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_42.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review/part_43.csv']

In [70]:
df = df.head(2000000)

In [42]:
df["stars"].value_counts()

stars
5.0    1062644
4.0     401878
1.0     246761
3.0     166745
2.0     121969
Name: count, dtype: int64

In [43]:
df["useful"].value_counts()

useful
0.0      1304699
1.0       418427
2.0       148245
3.0        60116
4.0        27608
          ...
137.0          1
106.0          1
117.0          1
139.0          1
140.0          1
Name: count, Length: 123, dtype: int64

In [75]:
# 假设df是你的DataFrame
value_counts = df["reads"].value_counts()

# 过滤掉计数小于10的数据，并将结果转换为DataFrame
filtered_counts = value_counts[value_counts >= 10].sort_index()

# 重命名索引为'name'，并将计数转换为字符串格式
result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})

# 转换为字典列表，每个字典代表一个记录
formatted_result = result_df.to_dict('records')

# 输出结果
print(formatted_result)

[{'name': False, 'num': '590494'}, {'name': True, 'num': '1409506'}]

In [76]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business.csv')

In [80]:
df = df.drop('length', axis=1)

In [82]:
df = df.rename(columns={'review_count': 'review'})

In [84]:
df = df.rename(columns={'postal_code': 'code'})

In [88]:
def generate_favorite(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(0, 20)
    elif 2 < stars <= 3:
        return random.randint(20, 70)
    elif 3 < stars <= 4:
        return random.randint(70, 160)
    elif 4 < stars <= 5:
        return random.randint(150, 220)
    else:
        return None

In [103]:
def generate_capacity(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(8, 15)
    elif 2 < stars <= 3:
        return random.randint(15, 25)
    elif 3 < stars <= 4:
        return random.randint(25, 40)
    elif 4 < stars <= 5:
        return random.randint(25, 50)
    else:
        return None

In [94]:
def generate_avgspend(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.randint(10, 20)
    elif 2 < stars <= 3:
        return random.randint(20, 35)
    elif 3 < stars <= 4:
        return random.randint(35, 80)
    elif 4 < stars <= 5:
        return random.randint(80, 160)
    else:
        return None

In [110]:
def generate_popular(stars):
    stars = float(stars)
    if 1 <= stars <= 2:
        return random.random() < 0.1
    elif 2 < stars <= 3:
        return random.random() < 0.3
    elif 3 < stars <= 4:
        return random.random() < 0.8
    elif 4 < stars <= 5:
        return random.random() < 0.99
    else:
        return None

In [89]:
df['favorites'] = df['stars'].apply(generate_favorite)

In [104]:
df['capacity'] = df['stars'].apply(generate_capacity)

In [95]:
df['avgspend'] = df['stars'].apply(generate_avgspend)

In [111]:
df['popular'] = df['stars'].apply(generate_popular)

In [112]:
df = df.drop('capacity', axis=1)

In [114]:
df = df[['business_id','name','address','city','state','code','stars','review','favorites','avgspend','popular','categories','feature']]

In [115]:
df.to_csv("/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business_mf.csv", index=False)

In [116]:
# 假设df是你的DataFrame
value_counts = df["popular"].value_counts()

# 过滤掉计数小于10的数据，并将结果转换为DataFrame
filtered_counts = value_counts[value_counts >= 10].sort_index()

# 重命名索引为'name'，并将计数转换为字符串格式
result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})

# 转换为字典列表，每个字典代表一个记录
formatted_result = result_df.to_dict('records')

# 输出结果
print(formatted_result)

[{'name': False, 'num': '49517'}, {'name': True, 'num': '100726'}]

In [117]:
output_folder = "/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip"
split_files = split_csv(df, output_folder)
print("分割的CSV文件列表：", split_files)

分割的CSV文件列表： ['/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_1.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_2.csv']

In [187]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/tip.csv')

In [189]:
df['date'] = pd.to_datetime(df['date'])

In [191]:
df= df.sort_values(by='date')

In [193]:
df = df.reset_index(drop=True)

In [203]:
df['num'] = df.groupby(['user_id', 'business_id']).cumcount() + 1

In [197]:
df = df.drop('date', axis=1)

In [198]:
df = df.drop('length', axis=1)

In [199]:
df = df.rename(columns={'compliment_count': 'compliment'})

In [200]:
def generate_amount():
    return round(random.uniform(2, 20), 1)

In [201]:
df['amount'] = [round(random.uniform(2, 20), 1) for _ in range(len(df))]

In [204]:
df = df[['user_id','business_id','compliment','amount','num','text','feature']]

In [207]:
output_folder = "/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip"
split_files = split_csv(df, output_folder)
print("分割的CSV文件列表：", split_files)

分割的CSV文件列表： ['/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_1.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_2.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_3.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_4.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_5.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_6.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_7.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_8.csv', '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/tip/part_9.csv']

In [133]:
df = pd.read_csv('/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/business_mf.csv')

In [134]:
df

,business_id,name,address,city,state,code,stars,review,favorites,avgspend,popular,categories,feature
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,5.0,7,220,160,True,"Doctors, Traditional Chinese Medicine, Naturop...","[0.5149855613708496, -0.2046436369419098, -0.3..."
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,3.0,15,36,27,False,"Shipping Centers, Local Services, Notaries, Ma...","[0.2881472706794739, -0.04402739554643631, -0...."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,3.5,22,134,56,True,"Department Stores, Shopping, Fashion, Home & G...","[0.49464067816734314, 0.022908760234713554, -0..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,4.0,80,98,49,True,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","[0.47613540291786194, 0.04090013727545738, -0...."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,4.5,13,215,116,True,"Brewpubs, Breweries, Food","[0.6412854790687561, 0.15557944774627686, -0.2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150238,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,3.0,13,22,22,False,"Nail Salons, Beauty & Spas","[0.4360079765319824, 0.15860453248023987, -0.6..."
150239,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,4.0,5,87,59,True,"Pets, Nurseries & Gardening, Pet Stores, Hobby...","[0.43686267733573914, 0.10853110998868942, -0...."
150240,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,3.5,8,77,67,False,"Shopping, Jewelry, Piercing, Toy Stores, Beaut...","[0.34829986095428467, 0.06677868217229843, -0...."
150241,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,4.0,24,115,70,False,"Fitness/Exercise Equipment, Eyewear & Optician...","[0.45862674713134766, 0.17515017092227936, -0...."
150242,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,4.5,9,164,136,True,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo","[0.19764001667499542, 0.24613741040229797, -0...."

### sample

In [135]:
base_directory = '/remote-home/cs_acmis_wsf/ai4dingo/yelp/vector/split_file/review'
base_filename = 'part_'
file_extension = '.csv'

In [136]:
dfs = []

# 使用循环读取part_1.csv到part_40.csv文件
for i in range(1, 41):  # 从1到40，包含40
    file_name = f"{base_filename}{i}{file_extension}"  # 构建文件名
    file_path = os.path.join(base_directory, file_name)  # 构建完整的文件路径
    df = pd.read_csv(file_path)  # 读取CSV文件
    dfs.append(df)  # 将DataFrame添加到列表中

In [137]:
df = pd.concat(dfs, ignore_index=True)

In [138]:
df

,review_id,stars,useful,funny,cool,likes,dislikes,views,reads,text,feature
0,KU_O5udG6zpxOg-VcAEodg,3.0,0.0,0.0,0.0,26,23,2,False,"If you decide to eat here, just be aware it is...","[0.41245171427726746, 0.1637980341911316, -0.2..."
1,saUsX_uimxRlCVr67Z4Jig,3.0,0.0,0.0,0.0,40,20,2,True,Family diner. Had the buffet. Eclectic assortm...,"[0.6022008061408997, 0.22512154281139374, 0.06..."
2,AqPFMleE6RsU23_auESxiA,5.0,1.0,0.0,1.0,138,46,15,True,"Wow! Yummy, different, delicious. Our favo...","[0.42374685406684875, 0.2453002780675888, 0.05..."
3,JrIxlS1TzJ-iCu79ul40cQ,1.0,1.0,2.0,1.0,17,12,0,False,I am a long term frequent customer of this est...,"[0.5036842226982117, 0.386075496673584, -0.108..."
4,_ZeMknuYdlQcUqng_Im3yg,5.0,2.0,0.0,0.0,114,42,14,True,Amazingly amazing wings and homemade bleu chee...,"[0.6822971701622009, 0.24157120287418365, 0.05..."
...,...,...,...,...,...,...,...,...,...,...,...
3999995,k3UycIKJVeppV64Ar2IDFg,4.0,0.0,0.0,0.0,77,26,7,True,Nice courtyard with surprisingly good food for...,"[0.5556442737579346, 0.2639174461364746, -0.03..."
3999996,SXkQl5rLAwStkXwUJzZcQw,4.0,0.0,0.0,0.0,72,26,10,False,It was my first time eating there. The food an...,"[0.5749701857566833, 0.36599236726760864, -0.0..."
3999997,jMC9vtsNE_6WM1xqREZNJA,5.0,0.0,0.0,0.0,123,42,13,True,This place warms your heart! Throw-back atmos...,"[0.5249049067497253, 0.26615262031555176, 0.07..."
3999998,hsKomrRKPlQiAJ4sMjRYIg,5.0,1.0,1.0,0.0,96,45,15,True,I love everything about this place! It's smal...,"[0.753829836845398, 0.16873358190059662, -0.05..."
3999999,MHoxwBwmNHNUDU309QhQbQ,5.0,0.0,2.0,1.0,132,40,18,True,The lady who was my server was amazing! I had...,"[0.24697978794574738, 0.5245411396026611, -0.1..."

In [146]:
# 假设df是你的DataFrame
value_counts = df["reads"].value_counts()

# 过滤掉计数小于10的数据，并将结果转换为DataFrame
filtered_counts = value_counts[value_counts >= 10].sort_index()

# 重命名索引为'name'，并将计数转换为字符串格式
result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})

# 转换为字典列表，每个字典代表一个记录
formatted_result = result_df.to_dict('records')

# 输出结果
print(formatted_result)

[{'name': False, 'num': '1178682'}, {'name': True, 'num': '2821318'}]

In [208]:
df

,user_id,business_id,compliment,amount,num,text,feature
0,rCumu_NyXfbyq16cP8vOEw,cXSyVvOr9YRN9diDkaWs0Q,0,14.9,1,Simply the best breakfast around!! The staff i...,"[0.6405475735664368, 0.17660640180110931, 0.06..."
1,LT_JU6bY75H918eKnnXeVQ,kLYhipAEvdT1ORfluX5gbw,0,2.2,1,Crunchy French toast is amazing!,"[0.25802168250083923, 0.15587060153484344, 0.1..."
2,sxZX1armKzagQxDnbvPnkw,gTC8IQ_i8zXytWSly3Ttvg,0,11.6,1,"Lunch specials are great, especially their hom...","[0.36990439891815186, 0.017034143209457397, 0...."
3,KI4UutWtai0UKZ6ZK2pg2Q,P3bw4h4kCaMaYqGGNLt3Jg,0,17.4,1,"Low selection, quiet","[0.417603075504303, 0.23099857568740845, 0.317..."
4,C14KW1jjKM8QlYfMyzP1sQ,aUjJ_x1KuvWmqIErhdaHzg,0,4.4,1,"Pretty good pad thai, but when I asked for lim...","[0.5951403975486755, 0.2372429370880127, -0.10..."
...,...,...,...,...,...,...,...
851028,vbQVYwb245MCFhqxg9aSng,7_5gXg2aG_wrJ18wdkDymQ,0,8.4,1,Great local spot with delicious food and live ...,"[0.44298797845840454, 0.13415025174617767, -0...."
851029,u8awpvumycJ6nR6Dn5tohQ,NHJa__j-wYQkwlaYWGz4Xg,0,6.6,1,Went above and beyond!,"[0.5153499245643616, 0.11985791474580765, 0.22..."
851030,tXOUDSVa51nJrX2ip9PdpA,13M0Y9AqznYGihb0zdIOlA,0,15.9,1,Amazing service!! I'm and out in no time! Beat...,"[0.32804355025291443, 0.4703589975833893, 0.03..."
851031,zD5pAdi4PDU1D1dO3c56lA,6P7MthfuntKbl2ZE2CCbAQ,0,6.2,1,Great service and beautiful nails!! Love my na...,"[0.3359599709510803, 0.23242567479610443, 0.06..."
851032,giQSReOdlfwPd9dND2FvDg,Qji91RHuT2pznRmv_CUYJQ,0,7.2,1,Donation drop off hours (non-clothing items - ...,"[0.4545551836490631, 0.09608332812786102, 0.16..."

In [211]:
# 假设df是你的DataFrame
value_counts = df["num"].value_counts()

# 过滤掉计数小于10的数据，并将结果转换为DataFrame
filtered_counts = value_counts[value_counts >= 10].sort_index()

# 重命名索引为'name'，并将计数转换为字符串格式
result_df = pd.DataFrame({'name': filtered_counts.index, 'num': filtered_counts.values.astype(str)})

# 转换为字典列表，每个字典代表一个记录
formatted_result = result_df.to_dict('records')

# 输出结果
print(formatted_result)

[{'name': 1, 'num': '739837'}, {'name': 2, 'num': '64514'}, {'name': 3, 'num': '18278'}, {'name': 4, 'num': '8450'}, {'name': 5, 'num': '4726'}, {'name': 6, 'num': '3070'}, {'name': 7, 'num': '2106'}, {'name': 8, 'num': '1529'}, {'name': 9, 'num': '1159'}, {'name': 10, 'num': '920'}, {'name': 11, 'num': '735'}, {'name': 12, 'num': '610'}, {'name': 13, 'num': '517'}, {'name': 14, 'num': '438'}, {'name': 15, 'num': '384'}, {'name': 16, 'num': '322'}, {'name': 17, 'num': '271'}, {'name': 18, 'num': '234'}, {'name': 19, 'num': '205'}, {'name': 20, 'num': '176'}, {'name': 21, 'num': '160'}, {'name': 22, 'num': '145'}, {'name': 23, 'num': '130'}, {'name': 24, 'num': '109'}, {'name': 25, 'num': '102'}, {'name': 26, 'num': '92'}, {'name': 27, 'num': '85'}, {'name': 28, 'num': '76'}, {'name': 29, 'num': '70'}, {'name': 30, 'num': '63'}, {'name': 31, 'num': '57'}, {'name': 32, 'num': '50'}, {'name': 33, 'num': '47'}, {'name': 34, 'num': '41'}, {'name': 35, 'num': '34'}, {'name': 36, 'num': '31'}, {'name': 37, 'num': '29'}, {'name': 38, 'num': '29'}, {'name': 39, 'num': '29'}, {'name': 40, 'num': '28'}, {'name': 41, 'num': '28'}, {'name': 42, 'num': '28'}, {'name': 43, 'num': '26'}, {'name': 44, 'num': '25'}, {'name': 45, 'num': '25'}, {'name': 46, 'num': '25'}, {'name': 47, 'num': '22'}, {'name': 48, 'num': '20'}, {'name': 49, 'num': '20'}, {'name': 50, 'num': '20'}, {'name': 51, 'num': '19'}, {'name': 52, 'num': '19'}, {'name': 53, 'num': '19'}, {'name': 54, 'num': '19'}, {'name': 55, 'num': '19'}, {'name': 56, 'num': '19'}, {'name': 57, 'num': '18'}, {'name': 58, 'num': '17'}, {'name': 59, 'num': '15'}, {'name': 60, 'num': '15'}, {'name': 61, 'num': '15'}, {'name': 62, 'num': '15'}, {'name': 63, 'num': '15'}, {'name': 64, 'num': '15'}, {'name': 65, 'num': '15'}, {'name': 66, 'num': '15'}, {'name': 67, 'num': '15'}, {'name': 68, 'num': '15'}, {'name': 69, 'num': '15'}, {'name': 70, 'num': '15'}, {'name': 71, 'num': '15'}, {'name': 72, 'num': '15'}, {'name': 73, 'num': '15'}, {'name': 74, 'num': '15'}, {'name': 75, 'num': '14'}, {'name': 76, 'num': '14'}, {'name': 77, 'num': '13'}, {'name': 78, 'num': '12'}, {'name': 79, 'num': '12'}, {'name': 80, 'num': '12'}, {'name': 81, 'num': '11'}, {'name': 82, 'num': '11'}, {'name': 83, 'num': '10'}, {'name': 84, 'num': '10'}, {'name': 85, 'num': '10'}, {'name': 86, 'num': '10'}, {'name': 87, 'num': '10'}]